# -*- coding: utf-8 -*-
"""String to MD5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GfKvKMs6O4lGT1K1m4UhAh7G3MK4Nujx
"""

import hashlib

s=input("Enter the string : ")

output = hashlib.md5(s.encode())

print("String to MD5 : ", end ="")

print(output.hexdigest())